version: '3.8'

services:
  fire-keeper:
    domainname: campfire-on-the-wall
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
      - 3001:3001
    environment:
      - NODE_ENV=development
      - VITE_SERVER_IP=http://109.232.28.168/  
      - VITE_SERVER_URL=https://campfire-on-the-wall.com
      - BACKUP_FILE_PREFIX=cotw-backup_
    volumes:
      # To develop and enable hot reload
      - ./frontend:/app/frontend
      - ./backend:/app/backend
      # To gather data
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /etc/hostname:/host/etc/hostname:ro
      - /backup/archives:/host/backup:ro
      - ../../../certificates/ssl/certificate_files/live/campfire-on-the-wall.com/fullchain.pem:/host/certificates/fullchain.pem:ro # SSL certificate path Adjust path as needed
    networks:
      campfire-on-the-wall-net:
        ipv4_address: 10.1.0.177
networks:
  campfire-on-the-wall-net:
    name: campfire-on-the-wall-net
    external: true
